name: CardFlow
options:
  bundleIdPrefix: com.cardflow
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "JLV37S2CYD"

targets:
  CardFlow:
    type: application
    platform: iOS
    sources:
      - CardFlow
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cardflow.app
        INFOPLIST_FILE: CardFlow/Info.plist
        CODE_SIGN_ENTITLEMENTS: CardFlow/CardFlow.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
    entitlements:
      path: CardFlow/CardFlow.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.cardflow.app
        com.apple.developer.icloud-services:
          - CloudDocuments
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.com.cardflow.app
