name: Plastik
options:
  bundleIdPrefix: com.plastikapp
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "JLV37S2CYD"
    CODE_SIGN_STYLE: Automatic

targets:
  Plastik:
    type: application
    platform: iOS
    sources:
      - Plastik
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.plastikapp.ios
        INFOPLIST_FILE: Plastik/Info.plist
        CODE_SIGN_ENTITLEMENTS: Plastik/Plastik.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
        TARGETED_DEVICE_FAMILY: "1,2"
    entitlements:
      path: Plastik/Plastik.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.plastikapp.ios
        com.apple.developer.icloud-services:
          - CloudKit
          - CloudDocuments
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.com.plastikapp.ios
    dependencies:
      - target: PlastikWidgetExtension

  PlastikWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - PlastikWidget
      - path: Plastik/Models
        buildPhase: sources
      - path: Plastik/Utilities/Constants.swift
        buildPhase: sources
      - path: Plastik/Utilities/Extensions.swift
        buildPhase: sources
      - path: Plastik/Services/DataFeedService.swift
        buildPhase: sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.plastikapp.ios.widget
        INFOPLIST_FILE: PlastikWidget/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        SKIP_INSTALL: "YES"
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
